sudo: required

dist: xenial

language: go

go_import_path: istio.io/manager

go:
  - 1.7.x

jdk:
  - oraclejdk8

env:
  global:
    - BAZEL_VERSION=0.4.3

addons:
  apt:
    packages:
      - wget

cache:
  directories:
    - $HOME/tools
    - $HOME/bazel/outbase

before_install:
  - mkdir -p ${HOME}/tools ${HOME}/bazel
  - cd ${HOME}/tools
  - wget -nc "https://github.com/bazelbuild/bazel/releases/download/${BAZEL_VERSION}/bazel_${BAZEL_VERSION}-linux-x86_64.deb"
  - sudo dpkg -i bazel_${BAZEL_VERSION}-linux-x86_64.deb
  - sudo apt-get -f install -qqy
  - cd ${TRAVIS_BUILD_DIR}
  - cat .bazelrc.travis > .bazelrc

install:
  - touch platform/kube/config
  - bazel --output_base=${HOME}/bazel/outbase build //...
  - bin/init.sh

script:
  - bazel --output_base=${HOME}/bazel/outbase test //...

notifications:
  slack: istio-dev:wEEEbaabdP5ieCgDOFetA9nX
