defaults: &defaults
  working_directory: /go/src/istio.io/pilot
  docker:
    - image: lyft/envoy-build:44d539cb572d04c81b62425373440c54934cf267

version: 2
jobs:
   build:
     <<: *defaults
     resource_class: xlarge
     steps:
       - checkout
       - run: bin/e2e.sh -circleci

workflows:
  version: 2
  all:
    jobs:
      - build
